### ISSUE TITLE
Migrate to Kotlin Multiplatform

### ISSUE THREAD

**Issue by jeffnyauke** [google/generative-ai-android#14]
Migrate to Kotlin Multiplatform in order to target more platforms

**Comment by daymxn** [comment]
We had a long discussion about this internally before the initial development of the SDK, and even have a doc going over it. 

It's definitely something we're interested in, but we're wanting to wait until the android/swift SDKs reach more stable versioning before reaching a conclusion on whether to move forward with it or not. It'll take a moderate amount of additional overhead to implement and maintain, so we'd rather keep our focus on the core SDK right now- and then re-evaluate when API changes are less likely (such as a `1.0.0`+ release).

I'll leave this open until we reach a conclusion down the road, such that other folks can vocalize their support as well. As always, it's easiest to justify the overhead for something that a large amount of people want/need.

**Comment by PatilShreyas** [comment]
Till the time official SDK is released, a forked version can be used for Multiplatform which has similar API: https://github.com/PatilShreyas/generative-ai-kmp

**Comment by krisbitney** [comment]
I'm super curious about why you decided not to support Kotlin Multiplatform. Which SDK features would be difficult to implement?

**Comment by takahirom** [comment]
@PatilShreyas
As we can't create an issue for the repository, could you update to the latest version of Gemini? Being able to specify `responseMimeType = "application/json"` is especially essential for most projects.

**Comment by PatilShreyas** [comment]
@takahirom sure. Give me some time.

**Comment by PatilShreyas** [comment]
@takahirom here you go! _Released_ **[0.9.0-1.0.0](https://github.com/PatilShreyas/generative-ai-kmp/releases/tag/v0.9.0-1.0.0)** 🚀

```kotlin
implementation("dev.shreyaspatil.generativeai:generativeai-google:0.9.0-1.0.0") // or `0.9.0-1.0.0-wasm` for wasm target
```

**Comment by akardas16** [comment]
> [@takahirom](https://github.com/takahirom) here you go! _Released_ **[0.9.0-1.0.0](https://github.com/PatilShreyas/generative-ai-kmp/releases/tag/v0.9.0-1.0.0)** 🚀
> 
> implementation("dev.shreyaspatil.generativeai:generativeai-google:0.9.0-1.0.0") // or `0.9.0-1.0.0-wasm` for wasm target

it is also not compatible with latest version of ktor. I am getting below error

```
java.lang.NoClassDefFoundError: Failed resolution of: Lio/ktor/client/plugins/HttpTimeout;
	at io.ktor.client.engine.cio.CIOEngine.<init>(CIOEngine.kt:29)
	at io.ktor.client.engine.cio.CIO.create(CIOCommon.kt:35)
	at io.ktor.client.HttpClientKt.HttpClient(HttpClient.kt:612)
```

**Comment by PatilShreyas** [comment]
@adamglin0 I'll update it to latest ktor on my forked repo, stay tuned.

**Comment by PatilShreyas** [comment]
It's done, I've released [`v0.9.0-1.1.0`](https://github.com/PatilShreyas/generative-ai-kmp/releases/tag/v0.9.0-1.1.0) 🚀. 

I'll figure out in future if we should do independent versioning or not. Meanwhile, I've not added any docs so far since API was exactly compatible with official Android SDK. But since it's now ***deprecated***, will try to add docs as well in the coming time.


([Maven releases](https://central.sonatype.com/search?q=g:dev.shreyaspatil.generativeai&smo=true))
